#include <TRandom.h>
#include <iostream>

using namespace std;

int main()
{
  // Output 16 random numbers generated by ROOT.
  gRandom->SetSeed(0);
  for(int i = 0; i < 16; ++i) {
    cout << gRandom->Rndm() << endl;
  }
  return 0;
}
